import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { useAuthStore } from "@/store/auth.store";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";

export const Route = createFileRoute("/app/settings")({
  component: SettingsPage,
});

type StorageMode = "local" | "minio";

function SettingsPage() {
  const email = useAuthStore((s) => s.email);
  const serverUrl = useAuthStore((s) => s.serverUrl);

  const [mode, setMode] = useState<StorageMode>("local");
  const [basePath, setBasePath] = useState("/home/user/neuralops/");
  const [endpoint, setEndpoint] = useState("");
  const [bucket, setBucket] = useState("");
  const [accessKey, setAccessKey] = useState("");
  const [secretKey, setSecretKey] = useState("");

  function handleSave() {
    toast.success("Storage settings saved");
  }

  return (
    <div className="mx-auto max-w-2xl space-y-6 p-8">
      <h1 className="text-lg font-semibold text-foreground">Settings</h1>

      <div className="rounded-lg border border-border bg-card p-6">
        <h2 className="text-sm font-semibold">Account</h2>
        <dl className="mt-4 space-y-3 text-sm">
          <div className="flex justify-between">
            <dt className="text-foreground-muted">Email</dt>
            <dd>{email}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-foreground-muted">Connected server</dt>
            <dd className="truncate">{serverUrl}</dd>
          </div>
        </dl>
      </div>

      <div className="rounded-lg border border-border bg-card p-6">
        <h2 className="text-sm font-semibold">Storage</h2>
        <p className="mt-1 text-xs text-foreground-muted">
          Where files generated by agents and models are stored.
        </p>

        <RadioGroup
          value={mode}
          onValueChange={(v) => setMode(v as StorageMode)}
          className="mt-4 grid grid-cols-2 gap-3"
        >
          <label
            htmlFor="mode-local"
            className={`flex cursor-pointer items-center gap-2 rounded-md border p-3 text-sm ${
              mode === "local"
                ? "border-primary bg-primary-tint text-foreground"
                : "border-border text-foreground-muted"
            }`}
          >
            <RadioGroupItem id="mode-local" value="local" />
            Local Folder
          </label>
          <label
            htmlFor="mode-minio"
            className={`flex cursor-pointer items-center gap-2 rounded-md border p-3 text-sm ${
              mode === "minio"
                ? "border-primary bg-primary-tint text-foreground"
                : "border-border text-foreground-muted"
            }`}
          >
            <RadioGroupItem id="mode-minio" value="minio" />
            MinIO / S3
          </label>
        </RadioGroup>

        {mode === "local" ? (
          <div className="mt-5 space-y-2">
            <Label htmlFor="basePath">Local Storage</Label>
            <Input
              id="basePath"
              value={basePath}
              onChange={(e) => setBasePath(e.target.value)}
              placeholder="/home/user/neuralops/"
            />
            <p className="text-xs text-foreground-muted">
              Files generated by agents and models will be saved here. Each
              project gets a subfolder using its slug.
            </p>
            <p className="text-xs text-foreground-muted">
              Example:{" "}
              <code className="rounded bg-muted px-1 py-0.5">
                {basePath.replace(/\/?$/, "/")}
                {"{project-slug}/"}
              </code>
            </p>
          </div>
        ) : (
          <div className="mt-5 space-y-3">
            <div className="space-y-1.5">
              <Label htmlFor="endpoint">Endpoint URL</Label>
              <Input
                id="endpoint"
                value={endpoint}
                onChange={(e) => setEndpoint(e.target.value)}
                placeholder="https://s3.example.com"
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="bucket">Bucket name</Label>
              <Input
                id="bucket"
                value={bucket}
                onChange={(e) => setBucket(e.target.value)}
                placeholder="neuralops"
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label htmlFor="accessKey">Access Key</Label>
                <Input
                  id="accessKey"
                  value={accessKey}
                  onChange={(e) => setAccessKey(e.target.value)}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="secretKey">Secret Key</Label>
                <Input
                  id="secretKey"
                  type="password"
                  value={secretKey}
                  onChange={(e) => setSecretKey(e.target.value)}
                />
              </div>
            </div>
            <p className="text-xs text-foreground-muted">
              Works with MinIO, AWS S3, Cloudflare R2, and any S3-compatible
              storage.
            </p>
          </div>
        )}

        <div className="mt-6 flex justify-end">
          <Button onClick={handleSave}>Save</Button>
        </div>
      </div>
    </div>
  );
}
