# Generated by Django 5.2.15 on 2026-06-30 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0002_remove_knowledgebase_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who owns and administrates this company.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
