# Generated by Django 5.2.15 on 2026-07-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_invite_system_and_operation_perms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'default_permissions': ('add', 'view', 'change', 'delete', 'invite', 'remove', 'archive', 'join')},
        ),
        migrations.AlterModelOptions(
            name='chattopic',
            options={'default_permissions': ('add', 'view', 'change', 'delete', 'invite', 'remove', 'archive', 'join')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': ('add', 'view', 'change', 'delete', 'invite', 'remove', 'archive', 'join')},
        ),
    ]
